In [1]:
import sys

In [2]:
sys.version

'3.10.4 (main, Apr 25 2023, 19:51:33) [GCC 9.4.0]'

In [1]:
import numpy as np

In [2]:
np.__version__

'1.24.2'

In [3]:
a = [1, 2, 3, 4]
b = [3, 4, 5, 6]

In [4]:
a + b

[1, 2, 3, 4, 3, 4, 5, 6]

In [5]:
a - b

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [6]:
a * b

TypeError: can't multiply sequence by non-int of type 'list'

In [7]:
a / b

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [8]:
a + 3

TypeError: can only concatenate list (not "int") to list

In [9]:
a * 3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [10]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.array([1, 2, 3])

array([1, 2, 3])

In [15]:
x = np.array(range(5))
y = np.array(range(6, 11))

In [16]:
x

array([0, 1, 2, 3, 4])

In [17]:
y

array([ 6,  7,  8,  9, 10])

In [18]:
x.shape

(5,)

In [19]:
y.shape

(5,)

In [20]:
x + y

array([ 6,  8, 10, 12, 14])

In [21]:
x - y

array([-6, -6, -6, -6, -6])

In [22]:
x * y

array([ 0,  7, 16, 27, 40])

In [23]:
x / y

array([0.        , 0.14285714, 0.25      , 0.33333333, 0.4       ])

In [24]:
x.ndim

1

In [25]:
y.ndim

1

In [26]:
x = np.array([[1, 2, 3], [4, 5, 6]])

In [27]:
x.shape

(2, 3)

In [28]:
x.ndim

2

In [35]:
y = np.array([[2, 3, 4], [5, 6, 7]])

In [30]:
y.shape

(2, 3)

In [31]:
y.ndim

2

In [36]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
y

array([[2, 3, 4],
       [5, 6, 7]])

In [38]:
y + x

array([[ 3,  5,  7],
       [ 9, 11, 13]])

In [39]:
y - x

array([[1, 1, 1],
       [1, 1, 1]])

In [40]:
y * x

array([[ 2,  6, 12],
       [20, 30, 42]])

In [41]:
y / x

array([[2.        , 1.5       , 1.33333333],
       [1.25      , 1.2       , 1.16666667]])

In [44]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
np.arange(12).reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [48]:
np.arange(12).reshape(2, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [49]:
np.arange(12).reshape(1, 1, 1, 3, 4)

array([[[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]]]]])

In [50]:
np.arange(24).reshape(2, 4, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [51]:
np.arange(6).reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [52]:
np.arange(6).reshape(1, 2, 3)

array([[[0, 1, 2],
        [3, 4, 5]]])

In [53]:
x = np.array([[1, 2, 3], [2, 3, 4]])
y = np.array([[1, 2], [1, 3], [2, 3]])

In [54]:
x

array([[1, 2, 3],
       [2, 3, 4]])

In [55]:
y

array([[1, 2],
       [1, 3],
       [2, 3]])

In [56]:
x.shape

(2, 3)

In [57]:
y.shape

(3, 2)

In [59]:
x @ y

array([[ 9, 17],
       [13, 25]])